-- 100+ Colorschemes and themes for random selection
return {
  -- Core Popular Themes
  { "catppuccin/nvim", name = "catppuccin", lazy = true },
  { "rose-pine/neovim", name = "rose-pine", lazy = true },
  { "folke/tokyonight.nvim", lazy = true },
  { "EdenEast/nightfox.nvim", lazy = true },
  { "rebelot/kanagawa.nvim", lazy = true },
  { "sainnhe/gruvbox-material", lazy = true },
  { "sainnhe/everforest", lazy = true },
  { "morhetz/gruvbox", lazy = true },
  { "dracula/vim", name = "dracula", lazy = true },
  { 
    "ayu-theme/ayu-vim", 
    lazy = true,
    config = function()
      vim.g.ayucolor = "dark"
    end
  },
  { "shaunsingh/nord.nvim", lazy = true },
  { "lunarvim/darkplus.nvim", lazy = true },
  { "Mofiqul/vscode.nvim", lazy = true },
  { "marko-cerovac/material.nvim", lazy = true },
  {
    "projekt0n/github-nvim-theme",
    name = "github-theme",
    lazy = true,
    config = function()
      require("github-theme").setup({
        options = {
          compile_path = vim.fn.stdpath('cache') .. '/github-theme',
          compile_file_suffix = '_compiled',
          hide_end_of_buffer = true,
          hide_nc_statusline = true,
          transparent = false,
          terminal_colors = true,
          dim_inactive = false,
          module_default = true,
          styles = {
            comments = 'italic',
            functions = 'NONE',
            keywords = 'NONE',
            variables = 'NONE',
            conditionals = 'NONE',
            constants = 'NONE',
            numbers = 'NONE',
            operators = 'NONE',
            strings = 'NONE',
            types = 'NONE',
          },
          inverse = {
            match_paren = false,
            visual = false,
            search = false,
          },
        }
      })
    end
  },
  
  -- Dark Themes Collection
  { "yashguptaz/calvera-dark.nvim", lazy = true },
  { "olivercederborg/poimandres.nvim", lazy = true },
  { "NTBBloodbath/doom-one.nvim", lazy = true },
  { "oxfist/night-owl.nvim", lazy = true },
  { "drewtempelmeyer/palenight.vim", lazy = true },
  { "nyoom-engineering/oxocarbon.nvim", lazy = true },
  { "ray-x/aurora", lazy = true },
  { "kvrohit/mellow.nvim", lazy = true },
  { "fenetikm/falcon", lazy = true },
  { "navarasu/onedark.nvim", lazy = true },
  { "loctvl842/monokai-pro.nvim", lazy = true },
  { "maxmx03/fluoromachine.nvim", lazy = true },
  { "glepnir/zephyr-nvim", lazy = true },
  { "cocopon/iceberg.vim", lazy = true },
  { "sainnhe/sonokai", lazy = true },
  { "tiagovla/tokyodark.nvim", lazy = true },
  { "Th3Whit3Wolf/one-nvim", lazy = true },
  { "Th3Whit3Wolf/space-nvim", lazy = true },
  { "shaunsingh/solarized.nvim", lazy = true },
  { "theniceboy/nvim-deus", lazy = true },
  { "NTBBloodbath/sweetie.nvim", lazy = true },
  { "zootedb0t/citruszest.nvim", lazy = true },
  { "kaiuri/nvim-juliana", lazy = true },
  { "dasupradyumna/midnight.nvim", lazy = true },
  { "ribru17/bamboo.nvim", lazy = true },
  { "sainnhe/edge", lazy = true },
  { "hardhackerlabs/theme-vim", lazy = true },
  { "askfiy/visual_studio_code", lazy = true },
  { "projekt0n/caret.nvim", lazy = true },
  { "lalitmee/cobalt2.nvim", lazy = true },
  { "kvrohit/rasmus.nvim", lazy = true },
  { "ldelossa/vimdark", lazy = true },
  { "phha/zenburn.nvim", lazy = true },
  { "bluz71/vim-moonfly-colors", lazy = true },
  { "cpea2506/one_monokai.nvim", lazy = true },
  { "yorickpeterse/vim-paper", lazy = true },
  { "iagorrr/noctishc.nvim", lazy = true },
  { "tomasiser/vim-code-dark", lazy = true },
  { "rockerBOO/boo-colorscheme-nvim", lazy = true },
  { "ray-x/starry.nvim", lazy = true },
  { "sindrets/oxocarbon-lua.nvim", lazy = true },
  { "ishan9299/nvim-solarized-lua", lazy = true },
  { "adisen99/codeschool.nvim", lazy = true },
  { "uloco/bluloco.nvim", lazy = true },
  { "arzg/vim-colors-xcode", lazy = true },
  { "vv9k/vim-github-dark", lazy = true },
  { "shaeinst/roshnivim-cs", lazy = true },
  { "datsfilipe/min-theme.nvim", lazy = true },
  
  -- Additional Premium Themes (40+ more)
  { "AlexvZyl/nordic.nvim", lazy = true },
  { "rmehri01/onenord.nvim", lazy = true },
  { "Shatur/neovim-ayu", lazy = true },
  { "RRethy/nvim-base16", lazy = true },
  { "tjdevries/colorbuddy.nvim", lazy = true },
  { "rktjmp/lush.nvim", lazy = true },
  { "savq/melange-nvim", lazy = true },
  { "Mofiqul/dracula.nvim", lazy = true },
  { "LunarVim/primer.nvim", lazy = true },
  { "ellisonleao/gruvbox.nvim", lazy = true },
  { "shaunsingh/moonlight.nvim", lazy = true },
  { "ChristianChiarulli/nvcode-color-schemes.vim", lazy = true },
  { "mhartington/oceanic-next", lazy = true },
  { "jacoborus/tender.vim", lazy = true },
  { "arcticicestudio/nord-vim", lazy = true },
  { "bluz71/vim-nightfly-guicolors", lazy = true },
  { "challenger-deep-theme/vim", name = "challenger-deep", lazy = true },
  { "lifepillar/vim-solarized8", lazy = true },
  { "NLKNguyen/papercolor-theme", lazy = true },
  { "sainnhe/forest-night", lazy = true },
  { "whatyouhide/vim-gotham", lazy = true },
  { "srcery-colors/srcery-vim", lazy = true },
  { "ajmwagar/vim-deus", lazy = true },
  { "KeitaNakamura/neodark.vim", lazy = true },
  { "joshdick/onedark.vim", lazy = true },
  { "aonemd/kuroi.vim", lazy = true },
  { "rakr/vim-one", lazy = true },
  { "wadackel/vim-dogrun", lazy = true },
  { "artanikin/vim-synthwave84", lazy = true },
  { "embark-theme/vim", name = "embark", lazy = true },
  { "jdsimcoe/abstract.vim", lazy = true },
  { "sts10/vim-pink-moon", lazy = true },
  { "fcpg/vim-fahrenheit", lazy = true },
  { "KabbAmine/yowish.vim", lazy = true },
  { "scheakur/vim-scheakur", lazy = true },
  { "danilo-augusto/vim-afterglow", lazy = true },
  { "tyrannicaltoucan/vim-deep-space", lazy = true },
  { "rakr/vim-two-firewatch", lazy = true },
  { "kristijanhusak/vim-hybrid-material", lazy = true },
  { "hzchirs/vim-material", lazy = true },
  { "Rigellute/rigel", lazy = true },
  { "connorholyday/vim-snazzy", lazy = true },
  { "arzg/vim-colors-xcode", lazy = true },
  { "chriskempson/base16-vim", lazy = true },
  { "w0ng/vim-hybrid", lazy = true },
  { "junegunn/seoul256.vim", lazy = true },
  { "nanotech/jellybeans.vim", lazy = true },
  { "altercation/vim-colors-solarized", lazy = true },
  { "tomasr/molokai", lazy = true },
  { "vim-scripts/wombat256.vim", lazy = true },
  { "jpo/vim-railscasts-theme", lazy = true },
  { "flazz/vim-colorschemes", lazy = true },
  { "rafi/awesome-vim-colorschemes", lazy = true },
  
  -- Modern Neovim-specific themes
  { "Yazeed1s/oh-lucy.nvim", lazy = true },
  { "andersevenrud/nordic.nvim", lazy = true },
  { "shaunsingh/oxocarbon.nvim", lazy = true },
  { "olimorris/onedarkpro.nvim", lazy = true },
  { "luisiacc/gruvbox-baby", lazy = true },
  { "sam4llis/nvim-tundra", lazy = true },
  { "Everblush/nvim", name = "everblush", lazy = true },
  { "kartikp10/noctis.nvim", lazy = true },
  { "shaeinst/roshnivim-cs", lazy = true },
  { "titanzero/zephyrium", lazy = true },
  { "Mofiqul/adwaita.nvim", lazy = true },
  { "ThemerCorp/themer.lua", lazy = true },
  { "B4mbus/oxocarbon-lua.nvim", lazy = true },
  { "LunarVim/lunar.nvim", lazy = true },
  { "kdheepak/monochrome.nvim", lazy = true },
  { "https://github.com/metalelf0/jellybeans-nvim", lazy = true },
  { "Yazeed1s/minimal.nvim", lazy = true },
  { "frenzyexists/aquarium-vim", lazy = true },
  { "Th3Whit3Wolf/onebuddy", lazy = true },
  { "PHSix/nvim-hybrid", lazy = true },
  { "kyazdani42/blue-moon", lazy = true },
  { "mcchrish/zenbones.nvim", lazy = true },
  { "rebelot/kanagawa.nvim", lazy = true },
  { "FrenzyExists/aquarium-vim", lazy = true },
  
  -- Light themes for variety
  { "NLKNguyen/papercolor-theme", lazy = true },
  { "rakr/vim-one", lazy = true },
  { "sonph/onehalf", lazy = true },
  { "andreasvc/vim-256noir", lazy = true },
  { "romainl/Apprentice", lazy = true },
  { "fcpg/vim-orbital", lazy = true },
  { "YorickPeterse/happy_hacking.vim", lazy = true },
  { "plan9-for-vimspace/acme-colors", lazy = true },
  { "vim-scripts/mayansmoke", lazy = true },
  { "neutaaaaan/iosvkem", lazy = true }
}

