-- UI and interface plugins
return {
  -- Lualine Status Bar
  {
    'nvim-lualine/lualine.nvim',
    dependencies = { 'nvim-tree/nvim-web-devicons' },
    config = function()
      local theme = _G.selected_theme or "auto"
      local lualine_themes = {
        -- Core Popular Themes
        ["gruvbox-material"] = "gruvbox",
        everforest = "everforest",
        darkplus = "onedark",
        github_dark = "github_dark",
        github_dark_default = "github_dark",
        github_dark_dimmed = "github_dark",
        github_dark_high_contrast = "github_dark",
        material = "material",
        vscode = "vscode",
        ayu = "ayu_dark",
        dracula = "dracula",
        catppuccin = "catppuccin",
        ["catppuccin-latte"] = "catppuccin",
        ["catppuccin-frappe"] = "catppuccin",
        ["catppuccin-macchiato"] = "catppuccin",
        ["catppuccin-mocha"] = "catppuccin",
        tokyonight = "tokyonight",
        ["tokyonight-night"] = "tokyonight",
        ["tokyonight-storm"] = "tokyonight",
        ["tokyonight-day"] = "tokyonight",
        ["tokyonight-moon"] = "tokyonight",
        nightfox = "nightfox",
        dayfox = "nightfox",
        dawnfox = "nightfox",
        duskfox = "nightfox",
        nordfox = "nightfox",
        terafox = "nightfox",
        carbonfox = "nightfox",
        kanagawa = "kanagawa",
        ["kanagawa-wave"] = "kanagawa",
        ["kanagawa-dragon"] = "kanagawa",
        ["kanagawa-lotus"] = "kanagawa",
        onedark = "onedark",
        nord = "nord",
        ["nord-vim"] = "nord",
        ["doom-one"] = "doom-one",
        poimandres = "poimandres",
        ["rose-pine"] = "rose-pine",
        ["rose-pine-main"] = "rose-pine",
        ["rose-pine-moon"] = "rose-pine",
        ["rose-pine-dawn"] = "rose-pine",
        onenord = "onenord",
        nordic = "nordic",
        gruvbox = "gruvbox",
        
        -- Dark Themes Collection
        calvera = "auto",
        ["night-owl"] = "auto",
        palenight = "palenight",
        oxocarbon = "auto",
        ["oxocarbon-lua"] = "auto",
        aurora = "auto",
        mellow = "auto",
        falcon = "auto",
        ["monokai-pro"] = "molokai",
        fluoromachine = "auto",
        zephyr = "auto",
        iceberg = "iceberg",
        sonokai = "sonokai",
        tokyodark = "auto",
        one = "onelight",
        space = "auto",
        solarized = "solarized_dark",
        ["solarized-lua"] = "solarized_dark",
        solarized8 = "solarized_dark",
        deus = "auto",
        sweetie = "auto",
        citruszest = "auto",
        juliana = "auto",
        midnight = "auto",
        bamboo = "auto",
        edge = "edge",
        hardhacker = "auto",
        visual_studio_code = "vscode",
        caret = "auto",
        cobalt2 = "auto",
        rasmus = "auto",
        vimdark = "auto",
        zenburn = "zenburn",
        moonfly = "moonfly",
        one_monokai = "molokai",
        paper = "auto",
        noctishc = "auto",
        codedark = "codedark",
        boo = "auto",
        starry = "auto",
        codeschool = "auto",
        bluloco = "auto",
        xcode = "auto",
        ["github-dark"] = "github_dark",
        roshni = "auto",
        ["min-theme"] = "auto",
        
        -- Additional Premium Themes
        ["neovim-ayu"] = "ayu_dark",
        ["base16-default-dark"] = "base16",
        ["base16-ocean"] = "base16",
        melange = "auto",
        primer_dark = "auto",
        moonlight = "auto",
        ["oceanic-next"] = "oceanicnext",
        tender = "auto",
        nightfly = "nightfly",
        challenger_deep = "auto",
        PaperColor = "PaperColor",
        ["forest-night"] = "auto",
        gotham = "auto",
        srcery = "auto",
        ["vim-deus"] = "auto",
        neodark = "auto",
        kuroi = "auto",
        ["vim-one"] = "onelight",
        ["vim-one-light"] = "onelight",
        dogrun = "auto",
        synthwave84 = "auto",
        embark = "auto",
        abstract = "auto",
        ["pink-moon"] = "auto",
        fahrenheit = "auto",
        yowish = "auto",
        scheakur = "auto",
        afterglow = "auto",
        ["deep-space"] = "auto",
        ["two-firewatch"] = "auto",
        ["hybrid-material"] = "auto",
        ["vim-material"] = "material",
        rigel = "auto",
        snazzy = "auto",
        hybrid = "auto",
        seoul256 = "seoul256",
        jellybeans = "jellybeans",
        ["jellybeans-nvim"] = "jellybeans",
        molokai = "molokai",
        wombat256 = "wombat",
        railscasts = "auto",
        
        -- Modern Neovim-specific themes
        ["oh-lucy"] = "auto",
        onedarkpro = "onedark",
        ["gruvbox-baby"] = "gruvbox",
        tundra = "auto",
        everblush = "auto",
        noctis = "auto",
        zephyrium = "auto",
        adwaita = "auto",
        lunar = "auto",
        monochrome = "auto",
        minimal = "auto",
        aquarium = "auto",
        onebuddy = "onelight",
        ["nvim-hybrid"] = "auto",
        ["blue-moon"] = "auto",
        zenbones = "auto",
        
        -- Light themes
        onehalflight = "onelight",
        ["256_noir"] = "auto",
        apprentice = "auto",
        orbital = "auto",
        happy_hacking = "auto",
        acme = "auto",
        mayansmoke = "auto",
        iosvkem = "auto",
        
        -- Classic vim themes
        desert = "auto",
        murphy = "auto",
        pablo = "auto",
        peachpuff = "auto",
        ron = "auto",
        shine = "auto",
        slate = "auto",
        torte = "auto",
        zellner = "auto",
        blue = "auto",
        darkblue = "auto",
        default = "auto",
        delek = "auto",
        evening = "auto",
        industry = "auto",
        koehler = "auto",
        morning = "auto",
        elflord = "auto"
      }
      require('lualine').setup({
        options = {
          theme              = lualine_themes[theme] or "auto",
  	  section_separators = { left = '', right = '' },
          component_separators = { left = '', right = '' },
          icons_enabled      = true,
        },
        sections = {
          lualine_a = { { 'mode', upper = false } },
          lualine_b = {
            { 'branch', icon = '' },
            { 'diff', colored = true, symbols = { added = '+', modified = '~', removed = '-' } },
            { 'diagnostics', sources = { 'nvim_lsp' } },
          },
          lualine_c = { { 'filename', path = 1 } },
          lualine_x = { 'encoding', 'fileformat', 'filetype' },
          lualine_y = { 'progress' },
          lualine_z = { 'location' },
        },
        extensions = { 'fugitive' },
      })
    end
  },

  -- Telescope & Which-Key
  {
    'nvim-telescope/telescope.nvim', 
    tag = '0.1.8',
    dependencies = { 'nvim-lua/plenary.nvim' }
  },
  {
    'folke/which-key.nvim',
    config = function() 
      require('which-key').setup() 
    end
  },
}

